/* Generated by Yosys 0.9 (git sha1 1979e0b) */

module \$paramod\auth_cam\TABLE_SIZE=16 (clk, rst_n, cfg_addr, cfg_wr_en, cfg_func_id, cfg_token, lookup_func_id, lookup_token, lookup_valid, lookup_ready, auth_pass, auth_done);
  wire _000_;
  wire _001_;
  wire [15:0] _002_;
  wire [15:0] _003_;
  wire [15:0] _004_;
  wire [15:0] _005_;
  wire [15:0] _006_;
  wire [15:0] _007_;
  wire [15:0] _008_;
  wire [15:0] _009_;
  wire [15:0] _010_;
  wire [15:0] _011_;
  wire [15:0] _012_;
  wire [15:0] _013_;
  wire [15:0] _014_;
  wire [15:0] _015_;
  wire [15:0] _016_;
  wire [15:0] _017_;
  wire [63:0] _018_;
  wire [63:0] _019_;
  wire [63:0] _020_;
  wire [63:0] _021_;
  wire [63:0] _022_;
  wire [63:0] _023_;
  wire [63:0] _024_;
  wire [63:0] _025_;
  wire [63:0] _026_;
  wire [63:0] _027_;
  wire [63:0] _028_;
  wire [63:0] _029_;
  wire [63:0] _030_;
  wire [63:0] _031_;
  wire [63:0] _032_;
  wire [63:0] _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire [15:0] _082_;
  wire _083_;
  wire [15:0] _084_;
  wire _085_;
  wire [15:0] _086_;
  wire _087_;
  wire [15:0] _088_;
  wire _089_;
  wire [15:0] _090_;
  wire _091_;
  wire [15:0] _092_;
  wire _093_;
  wire [15:0] _094_;
  wire _095_;
  wire [15:0] _096_;
  wire _097_;
  wire [15:0] _098_;
  wire _099_;
  wire [15:0] _100_;
  wire _101_;
  wire [15:0] _102_;
  wire _103_;
  wire [15:0] _104_;
  wire _105_;
  wire [15:0] _106_;
  wire _107_;
  wire [15:0] _108_;
  wire _109_;
  wire [15:0] _110_;
  wire _111_;
  wire [15:0] _112_;
  wire _113_;
  wire [63:0] _114_;
  wire [63:0] _115_;
  wire [63:0] _116_;
  wire [63:0] _117_;
  wire [63:0] _118_;
  wire [63:0] _119_;
  wire [63:0] _120_;
  wire [63:0] _121_;
  wire [63:0] _122_;
  wire [63:0] _123_;
  wire [63:0] _124_;
  wire [63:0] _125_;
  wire [63:0] _126_;
  wire [63:0] _127_;
  wire [63:0] _128_;
  wire [63:0] _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  output auth_done;
  reg auth_done;
  output auth_pass;
  reg auth_pass;
  input [3:0] cfg_addr;
  input [15:0] cfg_func_id;
  input [63:0] cfg_token;
  input cfg_wr_en;
  input clk;
  wire [31:0] i;
  input [15:0] lookup_func_id;
  output lookup_ready;
  input [63:0] lookup_token;
  input lookup_valid;
  input rst_n;
  reg [15:0] \table_func[0] ;
  reg [15:0] \table_func[10] ;
  reg [15:0] \table_func[11] ;
  reg [15:0] \table_func[12] ;
  reg [15:0] \table_func[13] ;
  reg [15:0] \table_func[14] ;
  reg [15:0] \table_func[15] ;
  reg [15:0] \table_func[1] ;
  reg [15:0] \table_func[2] ;
  reg [15:0] \table_func[3] ;
  reg [15:0] \table_func[4] ;
  reg [15:0] \table_func[5] ;
  reg [15:0] \table_func[6] ;
  reg [15:0] \table_func[7] ;
  reg [15:0] \table_func[8] ;
  reg [15:0] \table_func[9] ;
  reg [63:0] \table_tok[0] ;
  reg [63:0] \table_tok[10] ;
  reg [63:0] \table_tok[11] ;
  reg [63:0] \table_tok[12] ;
  reg [63:0] \table_tok[13] ;
  reg [63:0] \table_tok[14] ;
  reg [63:0] \table_tok[15] ;
  reg [63:0] \table_tok[1] ;
  reg [63:0] \table_tok[2] ;
  reg [63:0] \table_tok[3] ;
  reg [63:0] \table_tok[4] ;
  reg [63:0] \table_tok[5] ;
  reg [63:0] \table_tok[6] ;
  reg [63:0] \table_tok[7] ;
  reg [63:0] \table_tok[8] ;
  reg [63:0] \table_tok[9] ;
  assign _034_ = \table_func[0]  == lookup_func_id;
  assign _035_ = \table_func[1]  == lookup_func_id;
  assign _036_ = \table_func[2]  == lookup_func_id;
  assign _037_ = \table_func[3]  == lookup_func_id;
  assign _038_ = \table_func[4]  == lookup_func_id;
  assign _039_ = \table_func[5]  == lookup_func_id;
  assign _040_ = \table_func[6]  == lookup_func_id;
  assign _041_ = \table_func[7]  == lookup_func_id;
  assign _042_ = \table_func[8]  == lookup_func_id;
  assign _043_ = \table_func[9]  == lookup_func_id;
  assign _044_ = \table_func[10]  == lookup_func_id;
  assign _045_ = \table_func[11]  == lookup_func_id;
  assign _046_ = \table_func[12]  == lookup_func_id;
  assign _047_ = \table_func[13]  == lookup_func_id;
  assign _048_ = \table_func[14]  == lookup_func_id;
  assign _049_ = \table_func[15]  == lookup_func_id;
  assign _050_ = \table_tok[0]  == lookup_token;
  assign _051_ = \table_tok[1]  == lookup_token;
  assign _052_ = \table_tok[2]  == lookup_token;
  assign _053_ = \table_tok[3]  == lookup_token;
  assign _054_ = \table_tok[4]  == lookup_token;
  assign _055_ = \table_tok[5]  == lookup_token;
  assign _056_ = \table_tok[6]  == lookup_token;
  assign _057_ = \table_tok[7]  == lookup_token;
  assign _058_ = \table_tok[8]  == lookup_token;
  assign _059_ = \table_tok[9]  == lookup_token;
  assign _060_ = \table_tok[10]  == lookup_token;
  assign _061_ = \table_tok[11]  == lookup_token;
  assign _062_ = \table_tok[12]  == lookup_token;
  assign _063_ = \table_tok[13]  == lookup_token;
  assign _064_ = \table_tok[14]  == lookup_token;
  assign _065_ = \table_tok[15]  == lookup_token;
  assign _066_ = _034_ && _050_;
  assign _067_ = _035_ && _051_;
  assign _068_ = _036_ && _052_;
  assign _069_ = _037_ && _053_;
  assign _070_ = _038_ && _054_;
  assign _071_ = _039_ && _055_;
  assign _072_ = _040_ && _056_;
  assign _073_ = _041_ && _057_;
  assign _074_ = _042_ && _058_;
  assign _075_ = _043_ && _059_;
  assign _076_ = _044_ && _060_;
  assign _077_ = _045_ && _061_;
  assign _078_ = _046_ && _062_;
  assign _079_ = _047_ && _063_;
  assign _080_ = _048_ && _064_;
  assign _081_ = _049_ && _065_;
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      auth_pass <= 1'h0;
    else
      auth_pass <= _001_;
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      auth_done <= 1'h0;
    else
      auth_done <= _000_;
  always @(posedge clk)
      \table_tok[0]  <= _018_;
  always @(posedge clk)
      \table_tok[1]  <= _025_;
  always @(posedge clk)
      \table_tok[2]  <= _026_;
  always @(posedge clk)
      \table_tok[3]  <= _027_;
  always @(posedge clk)
      \table_tok[4]  <= _028_;
  always @(posedge clk)
      \table_tok[5]  <= _029_;
  always @(posedge clk)
      \table_tok[6]  <= _030_;
  always @(posedge clk)
      \table_tok[7]  <= _031_;
  always @(posedge clk)
      \table_tok[8]  <= _032_;
  always @(posedge clk)
      \table_tok[9]  <= _033_;
  always @(posedge clk)
      \table_tok[10]  <= _019_;
  always @(posedge clk)
      \table_tok[11]  <= _020_;
  always @(posedge clk)
      \table_tok[12]  <= _021_;
  always @(posedge clk)
      \table_tok[13]  <= _022_;
  always @(posedge clk)
      \table_tok[14]  <= _023_;
  always @(posedge clk)
      \table_tok[15]  <= _024_;
  always @(posedge clk)
      \table_func[0]  <= _002_;
  always @(posedge clk)
      \table_func[1]  <= _009_;
  always @(posedge clk)
      \table_func[2]  <= _010_;
  always @(posedge clk)
      \table_func[3]  <= _011_;
  always @(posedge clk)
      \table_func[4]  <= _012_;
  always @(posedge clk)
      \table_func[5]  <= _013_;
  always @(posedge clk)
      \table_func[6]  <= _014_;
  always @(posedge clk)
      \table_func[7]  <= _015_;
  always @(posedge clk)
      \table_func[8]  <= _016_;
  always @(posedge clk)
      \table_func[9]  <= _017_;
  always @(posedge clk)
      \table_func[10]  <= _003_;
  always @(posedge clk)
      \table_func[11]  <= _004_;
  always @(posedge clk)
      \table_func[12]  <= _005_;
  always @(posedge clk)
      \table_func[13]  <= _006_;
  always @(posedge clk)
      \table_func[14]  <= _007_;
  always @(posedge clk)
      \table_func[15]  <= _008_;
  assign _082_ = _083_ ? cfg_func_id : \table_func[15] ;
  assign _008_ = cfg_wr_en ? _082_ : \table_func[15] ;
  assign _084_ = _085_ ? cfg_func_id : \table_func[14] ;
  assign _007_ = cfg_wr_en ? _084_ : \table_func[14] ;
  assign _086_ = _087_ ? cfg_func_id : \table_func[13] ;
  assign _006_ = cfg_wr_en ? _086_ : \table_func[13] ;
  assign _088_ = _089_ ? cfg_func_id : \table_func[12] ;
  assign _005_ = cfg_wr_en ? _088_ : \table_func[12] ;
  assign _090_ = _091_ ? cfg_func_id : \table_func[11] ;
  assign _004_ = cfg_wr_en ? _090_ : \table_func[11] ;
  assign _092_ = _093_ ? cfg_func_id : \table_func[10] ;
  assign _003_ = cfg_wr_en ? _092_ : \table_func[10] ;
  assign _094_ = _095_ ? cfg_func_id : \table_func[9] ;
  assign _017_ = cfg_wr_en ? _094_ : \table_func[9] ;
  assign _096_ = _097_ ? cfg_func_id : \table_func[8] ;
  assign _016_ = cfg_wr_en ? _096_ : \table_func[8] ;
  assign _098_ = _099_ ? cfg_func_id : \table_func[7] ;
  assign _015_ = cfg_wr_en ? _098_ : \table_func[7] ;
  assign _100_ = _101_ ? cfg_func_id : \table_func[6] ;
  assign _014_ = cfg_wr_en ? _100_ : \table_func[6] ;
  assign _102_ = _103_ ? cfg_func_id : \table_func[5] ;
  assign _013_ = cfg_wr_en ? _102_ : \table_func[5] ;
  assign _104_ = _105_ ? cfg_func_id : \table_func[4] ;
  assign _012_ = cfg_wr_en ? _104_ : \table_func[4] ;
  assign _106_ = _107_ ? cfg_func_id : \table_func[3] ;
  assign _011_ = cfg_wr_en ? _106_ : \table_func[3] ;
  assign _108_ = _109_ ? cfg_func_id : \table_func[2] ;
  assign _010_ = cfg_wr_en ? _108_ : \table_func[2] ;
  assign _110_ = _111_ ? cfg_func_id : \table_func[1] ;
  assign _009_ = cfg_wr_en ? _110_ : \table_func[1] ;
  assign _112_ = _113_ ? cfg_func_id : \table_func[0] ;
  assign _002_ = cfg_wr_en ? _112_ : \table_func[0] ;
  assign _114_ = _083_ ? cfg_token : \table_tok[15] ;
  assign _083_ = cfg_addr == 4'hf;
  assign _024_ = cfg_wr_en ? _114_ : \table_tok[15] ;
  assign _115_ = _085_ ? cfg_token : \table_tok[14] ;
  assign _085_ = cfg_addr == 4'he;
  assign _023_ = cfg_wr_en ? _115_ : \table_tok[14] ;
  assign _116_ = _087_ ? cfg_token : \table_tok[13] ;
  assign _087_ = cfg_addr == 4'hd;
  assign _022_ = cfg_wr_en ? _116_ : \table_tok[13] ;
  assign _117_ = _089_ ? cfg_token : \table_tok[12] ;
  assign _089_ = cfg_addr == 4'hc;
  assign _021_ = cfg_wr_en ? _117_ : \table_tok[12] ;
  assign _118_ = _091_ ? cfg_token : \table_tok[11] ;
  assign _091_ = cfg_addr == 4'hb;
  assign _020_ = cfg_wr_en ? _118_ : \table_tok[11] ;
  assign _119_ = _093_ ? cfg_token : \table_tok[10] ;
  assign _093_ = cfg_addr == 4'ha;
  assign _019_ = cfg_wr_en ? _119_ : \table_tok[10] ;
  assign _120_ = _095_ ? cfg_token : \table_tok[9] ;
  assign _095_ = cfg_addr == 4'h9;
  assign _033_ = cfg_wr_en ? _120_ : \table_tok[9] ;
  assign _121_ = _097_ ? cfg_token : \table_tok[8] ;
  assign _097_ = cfg_addr == 4'h8;
  assign _032_ = cfg_wr_en ? _121_ : \table_tok[8] ;
  assign _122_ = _099_ ? cfg_token : \table_tok[7] ;
  assign _099_ = cfg_addr == 4'h7;
  assign _031_ = cfg_wr_en ? _122_ : \table_tok[7] ;
  assign _123_ = _101_ ? cfg_token : \table_tok[6] ;
  assign _101_ = cfg_addr == 4'h6;
  assign _030_ = cfg_wr_en ? _123_ : \table_tok[6] ;
  assign _124_ = _103_ ? cfg_token : \table_tok[5] ;
  assign _103_ = cfg_addr == 4'h5;
  assign _029_ = cfg_wr_en ? _124_ : \table_tok[5] ;
  assign _125_ = _105_ ? cfg_token : \table_tok[4] ;
  assign _105_ = cfg_addr == 4'h4;
  assign _028_ = cfg_wr_en ? _125_ : \table_tok[4] ;
  assign _126_ = _107_ ? cfg_token : \table_tok[3] ;
  assign _107_ = cfg_addr == 4'h3;
  assign _027_ = cfg_wr_en ? _126_ : \table_tok[3] ;
  assign _127_ = _109_ ? cfg_token : \table_tok[2] ;
  assign _109_ = cfg_addr == 4'h2;
  assign _026_ = cfg_wr_en ? _127_ : \table_tok[2] ;
  assign _128_ = _111_ ? cfg_token : \table_tok[1] ;
  assign _111_ = cfg_addr == 4'h1;
  assign _025_ = cfg_wr_en ? _128_ : \table_tok[1] ;
  assign _129_ = _113_ ? cfg_token : \table_tok[0] ;
  assign _113_ = ! cfg_addr;
  assign _018_ = cfg_wr_en ? _129_ : \table_tok[0] ;
  assign _000_ = lookup_valid ? 1'h1 : 1'h0;
  assign _130_ = _066_ ? 1'h1 : 1'h0;
  assign _131_ = _067_ ? 1'h1 : _130_;
  assign _132_ = _068_ ? 1'h1 : _131_;
  assign _133_ = _069_ ? 1'h1 : _132_;
  assign _134_ = _070_ ? 1'h1 : _133_;
  assign _135_ = _071_ ? 1'h1 : _134_;
  assign _136_ = _072_ ? 1'h1 : _135_;
  assign _137_ = _073_ ? 1'h1 : _136_;
  assign _138_ = _074_ ? 1'h1 : _137_;
  assign _139_ = _075_ ? 1'h1 : _138_;
  assign _140_ = _076_ ? 1'h1 : _139_;
  assign _141_ = _077_ ? 1'h1 : _140_;
  assign _142_ = _078_ ? 1'h1 : _141_;
  assign _143_ = _079_ ? 1'h1 : _142_;
  assign _144_ = _080_ ? 1'h1 : _143_;
  assign _145_ = _081_ ? 1'h1 : _144_;
  assign _001_ = lookup_valid ? _145_ : auth_pass;
  assign i = 32'd16;
  assign lookup_ready = 1'h1;
endmodule

module fallback_bridge(clk, rst_n, fail_valid, fail_func_id, fail_token, host_ready, irq_valid, irq_data);
  wire [2:0] _00_;
  wire [63:0] _01_;
  wire [63:0] _02_;
  wire [63:0] _03_;
  wire [63:0] _04_;
  wire [63:0] _05_;
  wire [1:0] _06_;
  wire [1:0] _07_;
  wire [63:0] _08_;
  wire [31:0] _09_;
  wire [31:0] _10_;
  wire [31:0] _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire [63:0] _20_;
  wire _21_;
  wire [63:0] _22_;
  wire _23_;
  wire [63:0] _24_;
  wire _25_;
  wire [63:0] _26_;
  wire _27_;
  wire [2:0] _28_;
  wire [31:0] _29_;
  input clk;
  reg [2:0] count;
  input [15:0] fail_func_id;
  input [63:0] fail_token;
  input fail_valid;
  input host_ready;
  output [63:0] irq_data;
  reg [63:0] irq_data;
  output irq_valid;
  reg [63:0] \mem[0] ;
  reg [63:0] \mem[1] ;
  reg [63:0] \mem[2] ;
  reg [63:0] \mem[3] ;
  reg [1:0] rd_ptr;
  input rst_n;
  reg [1:0] wr_ptr;
  assign _09_ = wr_ptr + 32'd1;
  assign _10_ = count + 32'd1;
  assign _11_ = rd_ptr + 32'd1;
  assign _12_ = count > 32'd0;
  assign _13_ = fail_valid && _15_;
  assign _14_ = host_ready && _12_;
  assign _15_ = count < 32'd4;
  assign irq_valid = | count;
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      rd_ptr <= 2'h0;
    else
      rd_ptr <= _06_;
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      wr_ptr <= 2'h0;
    else
      wr_ptr <= _07_;
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      count <= 3'h0;
    else
      count <= _00_;
  always @(posedge clk)
      irq_data <= _01_;
  always @(posedge clk)
      \mem[0]  <= _02_;
  always @(posedge clk)
      \mem[1]  <= _03_;
  always @(posedge clk)
      \mem[2]  <= _04_;
  always @(posedge clk)
      \mem[3]  <= _05_;
  function [63:0] _46_;
    input [63:0] a;
    input [255:0] b;
    input [3:0] s;
    casez (s) // synopsys parallel_case
      4'b???1:
        _46_ = b[63:0];
      4'b??1?:
        _46_ = b[127:64];
      4'b?1??:
        _46_ = b[191:128];
      4'b1???:
        _46_ = b[255:192];
      default:
        _46_ = a;
    endcase
  endfunction
  assign _08_ = _46_(64'hxxxxxxxxxxxxxxxx, { \mem[0] , \mem[1] , \mem[2] , \mem[3]  }, { _19_, _18_, _17_, _16_ });
  assign _16_ = rd_ptr == 2'h3;
  assign _17_ = rd_ptr == 2'h2;
  assign _18_ = rd_ptr == 2'h1;
  assign _19_ = ! rd_ptr;
  assign _20_ = _21_ ? { fail_func_id, fail_token[47:0] } : \mem[3] ;
  assign _21_ = wr_ptr == 2'h3;
  assign _05_ = _13_ ? _20_ : \mem[3] ;
  assign _22_ = _23_ ? { fail_func_id, fail_token[47:0] } : \mem[2] ;
  assign _23_ = wr_ptr == 2'h2;
  assign _04_ = _13_ ? _22_ : \mem[2] ;
  assign _24_ = _25_ ? { fail_func_id, fail_token[47:0] } : \mem[1] ;
  assign _25_ = wr_ptr == 2'h1;
  assign _03_ = _13_ ? _24_ : \mem[1] ;
  assign _26_ = _27_ ? { fail_func_id, fail_token[47:0] } : \mem[0] ;
  assign _27_ = ! wr_ptr;
  assign _02_ = _13_ ? _26_ : \mem[0] ;
  assign _01_ = _14_ ? _08_ : irq_data;
  assign _28_ = _13_ ? _10_[2:0] : count;
  assign _00_ = _14_ ? _29_[2:0] : _28_;
  assign _07_ = _13_ ? _09_[1:0] : wr_ptr;
  assign _06_ = _14_ ? _11_[1:0] : rd_ptr;
  assign _29_ = count - 32'd1;
endmodule

module hdu_top(clk, rst_n, s_axis_tdata, s_axis_tvalid, s_axis_tready, dispatch_slot, dispatch_valid, compute_done_slot, compute_done_valid, cfg_addr, cfg_wr_en, cfg_func_id, cfg_token, host_ready, host_irq);
  wire _0_;
  wire _1_;
  wire _2_;
  wire alloc_fail;
  wire [4:0] alloc_slot_id;
  wire alloc_success;
  wire alloc_valid;
  wire auth_done;
  wire auth_pass;
  wire cam_ready;
  input [3:0] cfg_addr;
  input [15:0] cfg_func_id;
  input [63:0] cfg_token;
  input cfg_wr_en;
  input clk;
  input [4:0] compute_done_slot;
  input compute_done_valid;
  output [4:0] dispatch_slot;
  output dispatch_valid;
  output host_irq;
  input host_ready;
  wire [15:0] req_func;
  wire [63:0] req_token;
  wire req_valid;
  input rst_n;
  input [511:0] s_axis_tdata;
  output s_axis_tready;
  input s_axis_tvalid;
  assign _0_ = auth_done & auth_pass;
  assign dispatch_valid = alloc_valid & alloc_success;
  assign _1_ = auth_done & _2_;
  assign _2_ = ~ auth_pass;
  slot_allocator ALLOC (
    .alloc_fail(alloc_fail),
    .alloc_slot_id(alloc_slot_id),
    .alloc_success(alloc_success),
    .alloc_valid(alloc_valid),
    .clk(clk),
    .free_en(compute_done_valid),
    .free_slot_id(compute_done_slot),
    .req_ready(),
    .req_valid(_0_),
    .rst_n(rst_n)
  );
  \$paramod\auth_cam\TABLE_SIZE=16  CAM (
    .auth_done(auth_done),
    .auth_pass(auth_pass),
    .cfg_addr(cfg_addr),
    .cfg_func_id(cfg_func_id),
    .cfg_token(cfg_token),
    .cfg_wr_en(cfg_wr_en),
    .clk(clk),
    .lookup_func_id(s_axis_tdata[447:432]),
    .lookup_ready(cam_ready),
    .lookup_token(s_axis_tdata[511:448]),
    .lookup_valid(s_axis_tvalid),
    .rst_n(rst_n)
  );
  fallback_bridge FB (
    .clk(clk),
    .fail_func_id(s_axis_tdata[447:432]),
    .fail_token(s_axis_tdata[511:448]),
    .fail_valid(_1_),
    .host_ready(host_ready),
    .irq_data(),
    .irq_valid(host_irq),
    .rst_n(rst_n)
  );
  assign dispatch_slot = alloc_slot_id;
  assign req_func = s_axis_tdata[447:432];
  assign req_token = s_axis_tdata[511:448];
  assign req_valid = s_axis_tvalid;
  assign s_axis_tready = 1'h1;
endmodule

module slot_allocator(clk, rst_n, req_valid, req_ready, free_slot_id, free_en, alloc_slot_id, alloc_success, alloc_fail, alloc_valid);
  wire _000_;
  wire [4:0] _001_;
  wire _002_;
  wire [31:0] _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire [4:0] _067_;
  wire [4:0] _068_;
  wire [4:0] _069_;
  wire [4:0] _070_;
  wire [4:0] _071_;
  wire [4:0] _072_;
  wire [4:0] _073_;
  wire [4:0] _074_;
  wire [4:0] _075_;
  wire [4:0] _076_;
  wire [4:0] _077_;
  wire [4:0] _078_;
  wire [4:0] _079_;
  wire [4:0] _080_;
  wire [4:0] _081_;
  wire [4:0] _082_;
  wire [4:0] _083_;
  wire [4:0] _084_;
  wire [4:0] _085_;
  wire [4:0] _086_;
  wire [4:0] _087_;
  wire [4:0] _088_;
  wire [4:0] _089_;
  wire [4:0] _090_;
  wire [4:0] _091_;
  wire [4:0] _092_;
  wire [4:0] _093_;
  wire [4:0] _094_;
  wire [4:0] _095_;
  wire [4:0] _096_;
  wire [4:0] _097_;
  wire [4:0] _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  output alloc_fail;
  reg alloc_fail;
  output [4:0] alloc_slot_id;
  reg [4:0] alloc_slot_id;
  output alloc_success;
  reg alloc_success;
  output alloc_valid;
  reg [31:0] busy;
  input clk;
  input free_en;
  input [4:0] free_slot_id;
  wire [31:0] i;
  output req_ready;
  input req_valid;
  input rst_n;
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      busy <= 32'd0;
    else
      busy <= _003_;
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      alloc_slot_id <= 5'h00;
    else
      alloc_slot_id <= _001_;
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      alloc_success <= 1'h0;
    else
      alloc_success <= _002_;
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      alloc_fail <= 1'h0;
    else
      alloc_fail <= _000_;
  assign _004_ = free_slot_id == 5'h07;
  assign _005_ = free_en ? _195_ : busy[7];
  assign _006_ = busy[7] ? _005_ : 1'h1;
  assign _003_[7] = req_valid ? _006_ : _005_;
  assign _007_ = _008_ ? 1'h0 : busy[6];
  assign _008_ = free_slot_id == 5'h06;
  assign _009_ = free_en ? _007_ : busy[6];
  assign _010_ = busy[6] ? _009_ : 1'h1;
  assign _003_[6] = req_valid ? _010_ : _009_;
  assign _011_ = _012_ ? 1'h0 : busy[5];
  assign _012_ = free_slot_id == 5'h05;
  assign _013_ = free_en ? _011_ : busy[5];
  assign _014_ = busy[5] ? _013_ : 1'h1;
  assign _003_[5] = req_valid ? _014_ : _013_;
  assign _015_ = _016_ ? 1'h0 : busy[4];
  assign _016_ = free_slot_id == 5'h04;
  assign _017_ = free_en ? _015_ : busy[4];
  assign _018_ = busy[4] ? _017_ : 1'h1;
  assign _003_[4] = req_valid ? _018_ : _017_;
  assign _019_ = _020_ ? 1'h0 : busy[3];
  assign _020_ = free_slot_id == 5'h03;
  assign _021_ = free_en ? _019_ : busy[3];
  assign _022_ = busy[3] ? _021_ : 1'h1;
  assign _003_[3] = req_valid ? _022_ : _021_;
  assign _023_ = _024_ ? 1'h0 : busy[2];
  assign _024_ = free_slot_id == 5'h02;
  assign _025_ = free_en ? _023_ : busy[2];
  assign _026_ = busy[2] ? _025_ : 1'h1;
  assign _003_[2] = req_valid ? _026_ : _025_;
  assign _027_ = _028_ ? 1'h0 : busy[1];
  assign _028_ = free_slot_id == 5'h01;
  assign _029_ = free_en ? _027_ : busy[1];
  assign _030_ = busy[1] ? _029_ : 1'h1;
  assign _003_[1] = req_valid ? _030_ : _029_;
  assign _031_ = _032_ ? 1'h0 : busy[0];
  assign _032_ = ! free_slot_id;
  assign _033_ = free_en ? _031_ : busy[0];
  assign _034_ = busy[0] ? _033_ : 1'h1;
  assign _003_[0] = req_valid ? _034_ : _033_;
  assign _000_ = req_valid ? 1'h1 : 1'h0;
  assign _035_ = busy[0] ? 1'h0 : 1'h1;
  assign _038_ = busy[3] ? _037_ : 1'h1;
  assign _039_ = busy[4] ? _038_ : 1'h1;
  assign _040_ = busy[5] ? _039_ : 1'h1;
  assign _002_ = req_valid ? _066_ : 1'h0;
  assign _067_ = busy[0] ? alloc_slot_id : 5'h00;
  assign _068_ = busy[1] ? _067_ : 5'h01;
  assign _069_ = busy[2] ? _068_ : 5'h02;
  assign _070_ = busy[3] ? _069_ : 5'h03;
  assign _071_ = busy[4] ? _070_ : 5'h04;
  assign _072_ = busy[5] ? _071_ : 5'h05;
  assign _073_ = busy[6] ? _072_ : 5'h06;
  assign _074_ = busy[7] ? _073_ : 5'h07;
  assign _075_ = busy[8] ? _074_ : 5'h08;
  assign _076_ = busy[9] ? _075_ : 5'h09;
  assign _077_ = busy[10] ? _076_ : 5'h0a;
  assign _078_ = busy[11] ? _077_ : 5'h0b;
  assign _079_ = busy[12] ? _078_ : 5'h0c;
  assign _080_ = busy[13] ? _079_ : 5'h0d;
  assign _081_ = busy[14] ? _080_ : 5'h0e;
  assign _082_ = busy[15] ? _081_ : 5'h0f;
  assign _083_ = busy[16] ? _082_ : 5'h10;
  assign _084_ = busy[17] ? _083_ : 5'h11;
  assign _085_ = busy[18] ? _084_ : 5'h12;
  assign _086_ = busy[19] ? _085_ : 5'h13;
  assign _087_ = busy[20] ? _086_ : 5'h14;
  assign _088_ = busy[21] ? _087_ : 5'h15;
  assign _089_ = busy[22] ? _088_ : 5'h16;
  assign _090_ = busy[23] ? _089_ : 5'h17;
  assign _091_ = busy[24] ? _090_ : 5'h18;
  assign _092_ = busy[25] ? _091_ : 5'h19;
  assign _093_ = busy[26] ? _092_ : 5'h1a;
  assign _094_ = busy[27] ? _093_ : 5'h1b;
  assign _095_ = busy[28] ? _094_ : 5'h1c;
  assign _096_ = busy[29] ? _095_ : 5'h1d;
  assign _097_ = busy[30] ? _096_ : 5'h1e;
  assign _098_ = busy[31] ? _097_ : 5'h1f;
  assign _001_ = req_valid ? _098_ : alloc_slot_id;
  assign _036_ = busy[1] ? _035_ : 1'h1;
  assign _037_ = busy[2] ? _036_ : 1'h1;
  assign _041_ = busy[6] ? _040_ : 1'h1;
  assign _042_ = busy[7] ? _041_ : 1'h1;
  assign _043_ = busy[8] ? _042_ : 1'h1;
  assign _044_ = busy[9] ? _043_ : 1'h1;
  assign _045_ = busy[10] ? _044_ : 1'h1;
  assign _046_ = busy[11] ? _045_ : 1'h1;
  assign _047_ = busy[12] ? _046_ : 1'h1;
  assign _048_ = busy[13] ? _047_ : 1'h1;
  assign _049_ = busy[14] ? _048_ : 1'h1;
  assign _050_ = busy[15] ? _049_ : 1'h1;
  assign _051_ = busy[16] ? _050_ : 1'h1;
  assign _052_ = busy[17] ? _051_ : 1'h1;
  assign _053_ = busy[18] ? _052_ : 1'h1;
  assign _054_ = busy[19] ? _053_ : 1'h1;
  assign _055_ = busy[20] ? _054_ : 1'h1;
  assign _056_ = busy[21] ? _055_ : 1'h1;
  assign _057_ = busy[22] ? _056_ : 1'h1;
  assign _058_ = busy[23] ? _057_ : 1'h1;
  assign _059_ = busy[24] ? _058_ : 1'h1;
  assign _060_ = busy[25] ? _059_ : 1'h1;
  assign _061_ = busy[26] ? _060_ : 1'h1;
  assign _062_ = busy[27] ? _061_ : 1'h1;
  assign _063_ = busy[28] ? _062_ : 1'h1;
  assign _064_ = busy[29] ? _063_ : 1'h1;
  assign _065_ = busy[30] ? _064_ : 1'h1;
  assign _066_ = busy[31] ? _065_ : 1'h1;
  assign _099_ = _100_ ? 1'h0 : busy[31];
  assign _100_ = free_slot_id == 5'h1f;
  assign _101_ = free_en ? _099_ : busy[31];
  assign _102_ = busy[31] ? _101_ : 1'h1;
  assign _003_[31] = req_valid ? _102_ : _101_;
  assign _103_ = _104_ ? 1'h0 : busy[30];
  assign _104_ = free_slot_id == 5'h1e;
  assign _105_ = free_en ? _103_ : busy[30];
  assign _106_ = busy[30] ? _105_ : 1'h1;
  assign _003_[30] = req_valid ? _106_ : _105_;
  assign _107_ = _108_ ? 1'h0 : busy[29];
  assign _108_ = free_slot_id == 5'h1d;
  assign _109_ = free_en ? _107_ : busy[29];
  assign _110_ = busy[29] ? _109_ : 1'h1;
  assign _003_[29] = req_valid ? _110_ : _109_;
  assign _111_ = _112_ ? 1'h0 : busy[28];
  assign _112_ = free_slot_id == 5'h1c;
  assign _113_ = free_en ? _111_ : busy[28];
  assign _114_ = busy[28] ? _113_ : 1'h1;
  assign _003_[28] = req_valid ? _114_ : _113_;
  assign _115_ = _116_ ? 1'h0 : busy[27];
  assign _116_ = free_slot_id == 5'h1b;
  assign _117_ = free_en ? _115_ : busy[27];
  assign _118_ = busy[27] ? _117_ : 1'h1;
  assign _003_[27] = req_valid ? _118_ : _117_;
  assign _119_ = _120_ ? 1'h0 : busy[26];
  assign _120_ = free_slot_id == 5'h1a;
  assign _121_ = free_en ? _119_ : busy[26];
  assign _122_ = busy[26] ? _121_ : 1'h1;
  assign _003_[26] = req_valid ? _122_ : _121_;
  assign _123_ = _124_ ? 1'h0 : busy[25];
  assign _124_ = free_slot_id == 5'h19;
  assign _125_ = free_en ? _123_ : busy[25];
  assign _126_ = busy[25] ? _125_ : 1'h1;
  assign _003_[25] = req_valid ? _126_ : _125_;
  assign _127_ = _128_ ? 1'h0 : busy[24];
  assign _128_ = free_slot_id == 5'h18;
  assign _129_ = free_en ? _127_ : busy[24];
  assign _130_ = busy[24] ? _129_ : 1'h1;
  assign _003_[24] = req_valid ? _130_ : _129_;
  assign _131_ = _132_ ? 1'h0 : busy[23];
  assign _132_ = free_slot_id == 5'h17;
  assign _133_ = free_en ? _131_ : busy[23];
  assign _134_ = busy[23] ? _133_ : 1'h1;
  assign _003_[23] = req_valid ? _134_ : _133_;
  assign _135_ = _136_ ? 1'h0 : busy[22];
  assign _136_ = free_slot_id == 5'h16;
  assign _137_ = free_en ? _135_ : busy[22];
  assign _138_ = busy[22] ? _137_ : 1'h1;
  assign _003_[22] = req_valid ? _138_ : _137_;
  assign _139_ = _140_ ? 1'h0 : busy[21];
  assign _140_ = free_slot_id == 5'h15;
  assign _141_ = free_en ? _139_ : busy[21];
  assign _142_ = busy[21] ? _141_ : 1'h1;
  assign _003_[21] = req_valid ? _142_ : _141_;
  assign _143_ = _144_ ? 1'h0 : busy[20];
  assign _144_ = free_slot_id == 5'h14;
  assign _145_ = free_en ? _143_ : busy[20];
  assign _146_ = busy[20] ? _145_ : 1'h1;
  assign _003_[20] = req_valid ? _146_ : _145_;
  assign _147_ = _148_ ? 1'h0 : busy[19];
  assign _148_ = free_slot_id == 5'h13;
  assign _149_ = free_en ? _147_ : busy[19];
  assign _150_ = busy[19] ? _149_ : 1'h1;
  assign _003_[19] = req_valid ? _150_ : _149_;
  assign _151_ = _152_ ? 1'h0 : busy[18];
  assign _152_ = free_slot_id == 5'h12;
  assign _153_ = free_en ? _151_ : busy[18];
  assign _154_ = busy[18] ? _153_ : 1'h1;
  assign _003_[18] = req_valid ? _154_ : _153_;
  assign _155_ = _156_ ? 1'h0 : busy[17];
  assign _156_ = free_slot_id == 5'h11;
  assign _157_ = free_en ? _155_ : busy[17];
  assign _158_ = busy[17] ? _157_ : 1'h1;
  assign _003_[17] = req_valid ? _158_ : _157_;
  assign _159_ = _160_ ? 1'h0 : busy[16];
  assign _160_ = free_slot_id == 5'h10;
  assign _161_ = free_en ? _159_ : busy[16];
  assign _162_ = busy[16] ? _161_ : 1'h1;
  assign _003_[16] = req_valid ? _162_ : _161_;
  assign _163_ = _164_ ? 1'h0 : busy[15];
  assign _164_ = free_slot_id == 5'h0f;
  assign _165_ = free_en ? _163_ : busy[15];
  assign _166_ = busy[15] ? _165_ : 1'h1;
  assign _003_[15] = req_valid ? _166_ : _165_;
  assign _167_ = _168_ ? 1'h0 : busy[14];
  assign _168_ = free_slot_id == 5'h0e;
  assign _169_ = free_en ? _167_ : busy[14];
  assign _170_ = busy[14] ? _169_ : 1'h1;
  assign _003_[14] = req_valid ? _170_ : _169_;
  assign _171_ = _172_ ? 1'h0 : busy[13];
  assign _172_ = free_slot_id == 5'h0d;
  assign _173_ = free_en ? _171_ : busy[13];
  assign _174_ = busy[13] ? _173_ : 1'h1;
  assign _003_[13] = req_valid ? _174_ : _173_;
  assign _175_ = _176_ ? 1'h0 : busy[12];
  assign _176_ = free_slot_id == 5'h0c;
  assign _177_ = free_en ? _175_ : busy[12];
  assign _178_ = busy[12] ? _177_ : 1'h1;
  assign _003_[12] = req_valid ? _178_ : _177_;
  assign _179_ = _180_ ? 1'h0 : busy[11];
  assign _180_ = free_slot_id == 5'h0b;
  assign _181_ = free_en ? _179_ : busy[11];
  assign _182_ = busy[11] ? _181_ : 1'h1;
  assign _003_[11] = req_valid ? _182_ : _181_;
  assign _183_ = _184_ ? 1'h0 : busy[10];
  assign _184_ = free_slot_id == 5'h0a;
  assign _185_ = free_en ? _183_ : busy[10];
  assign _186_ = busy[10] ? _185_ : 1'h1;
  assign _003_[10] = req_valid ? _186_ : _185_;
  assign _187_ = _188_ ? 1'h0 : busy[9];
  assign _188_ = free_slot_id == 5'h09;
  assign _189_ = free_en ? _187_ : busy[9];
  assign _190_ = busy[9] ? _189_ : 1'h1;
  assign _003_[9] = req_valid ? _190_ : _189_;
  assign _191_ = _192_ ? 1'h0 : busy[8];
  assign _192_ = free_slot_id == 5'h08;
  assign _193_ = free_en ? _191_ : busy[8];
  assign _194_ = busy[8] ? _193_ : 1'h1;
  assign _003_[8] = req_valid ? _194_ : _193_;
  assign _195_ = _004_ ? 1'h0 : busy[7];
  assign alloc_valid = alloc_fail;
  assign i = 32'd32;
  assign req_ready = 1'h1;
endmodule
